CosmeticaShop.Web/Controllers/FavoritesController.cs
using System.Web.Mvc;
using CosmeticaShop.IServices;
using CosmeticaShop.IServices.Interfaces;
using CosmeticaShop.Services;
using CosmeticaShop.Web.Infrastructure;
using CosmeticaShop.Web.Models;

namespace CosmeticaShop.Web.Controllers
{
    public class FavoritesController : BaseController
    {

        private readonly IWishService _wishService = new WishService();
        private readonly IProductService _productService = new ProductService();
        public ActionResult Index()
        {
            var user = new WebUser();
            var model = new WishViewModel
            {
                Recommends = _productService.GetRecomendProducts(4)
            };
            if (user.IsAuthorized)
            {
                model.Wishes = _wishService.GetWishs(user.UserId);
            }
            else
                model.Wishes = _wishService.GetCookieWishs();
            return View(model);
        }

        /// <summary>
        /// Удалить товар из желаемого
        /// </summary>
        /// <param name="productId">Ид товара</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteWish(int productId)
        {
            var user = new WebUser();
            if (user.IsAuthorized)
            {
                var model = _wishService.DeleteWish(user.UserId, productId);
                return Json(model);
            }
            var cookieModel = _wishService.DeleteWish(null, productId);
            return Json(cookieModel);
        }
    }
}

CosmeticaShop.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CosmeticaShop.IServices.Enums;
using CosmeticaShop.IServices.Interfaces;
using CosmeticaShop.IServices.Models.Pagination;
using CosmeticaShop.Services;
using CosmeticaShop.Web.Infrastructure;
using CosmeticaShop.Web.Models;
using CosmeticaShop.IServices.Models.Product;

namespace CosmeticaShop.Web.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductService _productService = new ProductService();
        private readonly IOrderService _orderService = new OrderService();
        private readonly ICategoryService _categoryService = new CategoryService();
        /// <summary>
        /// Страница со списоком товаров
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(ProductFilterModel request)
        {
            SetSitePageSettings(EnumSitePage.Products);
            const int take = 21;
            var products = _productService.GetProducts(request);
    
            if (!request.Page.HasValue)
                request.Page = 1;
            if(request.CategoriesId==null)
                request.CategoriesId = new List<int>();
            // если не существует такой страницы
            if (request.Page > products.Count / take + 1)
            {
                request.Page = 1;
            }
                
            var model = new ProductsViewModel()
            {

                Products = products,
                Brands = _productService.GetAllBrandsBase(),
                Pagination = new PaginationModel(take)
                {
                    Count = products.Count,
                    Skip = ((int)request.Page - 1) * take,
                    Take = take,
                    PageNumber = (int)request.Page,
                    PageSize = (int)Math.Round(products.Count / Convert.ToDecimal(take))
                },
                Filter = request,
                Categories = _categoryService.GetAllCategories(),
                Tags = _productService.GetTagsForFilter(products)
            };
            model.Products = model.Products.Skip(model.Pagination.Skip).Take(model.Pagination.Take).ToList();
            return View(model);
        }
        /// <summary>
        /// Добавить товар в корзину
        /// </summary>
        /// <param name="productId">Ид товара</param>
        /// <param name="quantity">Количество товара</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddInCart(int productId, int quantity)
        {
            var user = new WebUser();
            if (user.IsAuthorized)
            {
                var response = _orderService.AddProductInCart(productId, user.UserId, quantity,false);
                return Json(response);
            }
            var responseCopokie = _orderService.AddProductInCoockieCart(productId, quantity,false);
            return Json(responseCopokie);
        }
        /// <summary>
        /// Добавить товар в желаемое
        /// </summary>
        /// <param name="productId">Ид товара</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddInWish(int productId)
        {
            var user = new WebUser();
            if (user.IsAuthorized)
            {
                var response = _productService.AddProductInWish(productId, user.UserId);
                return Json(response);
            }
            else
            {
                var response = _productService.AddProductInCoockieWish(productId);
                return Json(response);
            }
         
        }
        /// <summary>
        /// Детальная страница товара
        /// </summary>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            var product = _productService.GetProduct(id);
            var user = new WebUser();
            var possibilityReview = false;
            if (user.IsAuthorized)
            {
                possibilityReview = _productService.ValidationReview(user.UserId, id).IsSuccess;
            }
            var model = new ProductDetailsView()
            {
                Product = product,
                PossibilityReview = possibilityReview,
                SimilarProduct = _productService.GetSimilarProducts(id)
            };
            SetSitePageSettings(model.Product.Name, model.Product.SeoKeywords, model.Product.SeoDescription);
            return View(model);
        }
        /// <summary>
        /// Детальная страница товара
        /// </summary>
        /// <returns></returns>
        public ActionResult Detail(string productKeyUrl)
        {
            var product = _productService.GetProductByKeyUrl(productKeyUrl);
            if (!product.IsSuccess)
                return RedirectToAction("Index", "Home");
            var user = new WebUser();
            var possibilityReview = false;
            if (user.IsAuthorized)
            {
                possibilityReview = _productService.ValidationReview(user.UserId, product.Value.Id).IsSuccess;
            }
            var model = new ProductDetailsView()
            {
                Product = product.Value,
                PossibilityReview = possibilityReview,
                SimilarProduct = _productService.GetSimilarProducts(product.Value.Id)
            };
            SetSitePageSettings(model.Product.Name, model.Product.SeoKeywords, model.Product.SeoDescription);
            return View("~/Views/Product/Details.cshtml",model);
        }
        /// <summary>
        /// Добавить отзыв
        /// </summary>
        /// <param name="message">Сообщение отзыва</param>
        /// <param name="productId">Ид товара</param>
        /// <returns></returns>
        public ActionResult AddReview(string message,int productId)
        {
            var userId = new WebUser().UserId;
            var response = _productService.AddReview(userId, productId, message);
            return Json(response);
        }
        /// <summary>
        /// Получить тэги для фильтра
        /// </summary>
        /// <param name="products">Товары</param>
        /// <returns></returns>
        public ActionResult GetTagsForFilter(List<ProductBaseModel> products)
        {
            var res = _productService.GetTagsForFilter(products);
            return Json(res);
        }
    }
}

CosmeticaShop.Web/Views/Favorites/Index.cshtml
@using Newtonsoft.Json
@model CosmeticaShop.Web.Models.WishViewModel
@{
    ViewBag.Title = "Favorite";
}
@section Styles
{
    <style>
        .brand-list .col-md-3, .product-list.favo .col-md-3 {
            padding-right: 15px;
            padding-left: 15px;
        }
    </style>
}
@section Scripts {
    <script src="~/assets/js/Product/ProductFilter.js"></script>
    <script src="~/assets/js/Product/ProductModel.js"></script>
   
<script src="~/assets/js/Product/ProductLineView.js"></script>
    <script>
        var params = {};
        urlAddProductCart = '@Url.Action("AddInCart","Product")';
        urlAddProductWish = '@Url.Action("AddInWish","Product")';
        params.UrlGetProducts = '@Url.Action("Index","Product")';
        var urlDeleteWish = '@Url.Action("DeleteWish","Favorites")';
        params.Products = @Html.Raw(JsonConvert.SerializeObject(Model.Wishes.Select(x=> x.Product)));
        var ViewModel = new Product.ProductLineView(params);
        var paramsRecomends = {};
        paramsRecomends.Products = @Html.Raw(JsonConvert.SerializeObject(Model.Recommends));
        var RecomendtsModel = new Product.ProductLineView(paramsRecomends);
    </script>
}




<div class="row">
    <div class="col-md-12 white-container marginB-heigth-10">
        <div class="default-text navigation">
            <a href="@Url.Action("Index","Home")"> Principală </a> >  <span class="pink-darkk-text">Favorite</span></a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 white-container">
        <div class="row">
            @if (Model.Wishes.Count == 0)
            {
                <div class="block empty-favorit" align="center">
                    <i class="icon-very-big-pink-like"></i> <span>Nu ai adăugat nimic în favorite!</span>
                </div>
            }
            else
            {
                <div class="block" style="padding:2px;">
                    <div class="title-block" style="padding: 5px 10px 15px 10px;">
                        Favorite: <span data-bind="text:ViewModel.Products().filter(function(item){return item.IsWish() === true}).length"></span>
                    </div>
                    <div class="content">
                        <div class="row product-list favo row-flex" data-bind="foreach:ViewModel.Products().filter(function(item){return item.IsWish() === true})">
                           
                                <div class="col-xs-6 col-sm-4 col-md-3">
                                    <div class="item">
                                        <div class="product-content">
                                            <a data-bind="attr:{href:'@Url.Action("Detail","Product")/'+KeyUrl()}">
                                                <div class="product-img">
                                                    <img data-bind="attr:{src:PhotoUrl}" />
                                                    <!--ko if:DiscountPercent()!==0-->
                                                    <div class="discount" style="visibility:hidden;" data-bind="style:{visibility:DiscountPercent()!==0 ?'visible': 'hidden'}">
                                                        reducere  <div>
                                                            -<span data-bind="text:DiscountPercent">35</span>%
                                                        </div>
                                                    </div>
                                                    <!--/ko-->
                                                </div>
                                            </a>
                                            <a data-bind="attr:{href:'@Url.Action("Detail","Product")/'+KeyUrl()}">
                                                <div class="product-description title">
                                                    <span class="pink-text" data-bind="text:Name">

                                                    </span>
                                                </div>
                                            </a>
                                            <a data-bind="attr:{href:'@Url.Action("Detail","Product")/'+KeyUrl()}">
                                                <div class="product-description">
                                                    <span class="grey-text" data-bind="text:Description"></span>
                                                </div>
                                            </a>

                                            <div class="product-description">
                                                <!--ko if:DiscountPercent()!==0-->
                                                <span class="grey-price crossOut-pink" data-bind="text:Price()+' lei'"></span>
                                                <div>
                                                    <span class="pink-price" data-bind="text:DiscountPrice()+' lei'"></span>
                                                </div>
                                                <!--/ko-->
                                                <!--ko if:DiscountPercent()===0-->
                                                <span class="grey-price" data-bind="text:Price()+' lei'"></span>
                                                <!--/ko-->
                                            </div>
                                        </div>
                                        <div class="product-footer">
                                            <div class="pull-left" data-bind="click:DeleteWish">
                                                <i class="icon-pink-like "></i>
                                            </div>
                                            <div class="pull-right" data-bind="click:AddProductCart">
                                                <span style="cursor: pointer;">iau!</span> <i class="icon-product-cart"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                          
                        </div>

                    </div>
                </div>
            }
        </div>
    </div>

</div>

<div class="row">
    <section>
        <div class="section-name small">Recomandări pentru tine</div>
        <div class="row product-list row-flex" data-bind="foreach:RecomendtsModel.Products">

            <div class="col-xs-6 col-sm-4 col-md-3">
                <div class="item">
                    <div class="product-content">
                        <a data-bind="attr:{href:'@Url.Action("Detail","Product")/'+KeyUrl()}">
                            <div class="product-img">
                                <img data-bind="attr:{src:PhotoUrl}" />
                                <!--ko if:DiscountPercent()!==0-->
                                <div class="discount" style="visibility:hidden;" data-bind="style:{visibility:DiscountPercent()!==0 ?'visible': 'hidden'}">
                                    reducere  <div>
                                        -<span data-bind="text:DiscountPercent">35</span>%
                                    </div>
                                </div>
                                <!--/ko-->
                            </div>
                        </a>
                        <a data-bind="attr:{href:'@Url.Action("Detail","Product")/'+KeyUrl()}">
                            <div class="product-description title">
                                <span class="pink-text" data-bind="text:BrandName">

                                </span>
                            </div>
                        </a>
                        <a data-bind="attr:{href:'@Url.Action("Detail","Product")/'+KeyUrl()}">
                            <div class="product-description">
                                <span class="grey-text" data-bind="text:Name"></span>
                            </div>
                        </a>

                        <div class="product-description">
                            <!--ko if:DiscountPercent()!==0-->
                            <span class="grey-price crossOut-pink" data-bind="text:Price()+' lei'"></span>
                            <div>
                                <span class="pink-price" data-bind="text:DiscountPrice()+' lei'"></span>
                            </div>
                            <!--/ko-->
                            <!--ko if:DiscountPercent()===0-->
                            <span class="grey-price" data-bind="text:Price()+' lei'"></span>
                            <!--/ko-->
                        </div>
                    </div>
                    <div class="product-footer">
                        <!--ko if:IsWish-->
                        <div class="pull-left" data-bind="click:DeleteWish">
                            <i class="icon-pink-like "></i>
                        </div>
                        <!--/ko-->
                        <!--ko ifnot:IsWish-->
                        <div class="pull-left" data-bind="click:AddProductWish.bind($data,'pageWish')">
                            <i class="icon-like "></i>
                        </div>
                        <!--/ko-->
                        <div class="pull-right" data-bind="click:AddProductCart">
                            <span style="cursor: pointer;">iau!</span> <i class="icon-product-cart"></i>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </section>
</div>