CosmeticaShop.Web/Areas/Admin/Controllers/SitePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CosmeticaShop.IServices.Enums;
using CosmeticaShop.IServices.Interfaces;
using CosmeticaShop.IServices.Models;
using CosmeticaShop.IServices.Models.Base;
using CosmeticaShop.IServices.Models.Requests;
using CosmeticaShop.IServices.Models.Responses;
using CosmeticaShop.IServices.Models.SitePage;
using CosmeticaShop.IServices.Models.Slider;
using CosmeticaShop.Services;
using CosmeticaShop.Web.Infrastructure;

namespace CosmeticaShop.Web.Areas.Admin.Controllers
{
    [Authorization(Roles = ConstRoles.Admin)]
    public class SitePageController : Controller
    {
        #region [ Сервисы ]

        private ISitePageSevice _sitePageSevice = new SitePageSevice();

        #endregion

        #region [ Найстройки страниц ]

        public ActionResult Edit(EnumSitePage id)
        {
            var model = _sitePageSevice.GetSitePageModel(id);
            return View(model);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult UpdateSitePage(SitePageModel model)
        {
            var response = _sitePageSevice.UpdateSitePage(model);
            return RedirectToAction("Edit", new {id = model.Id});
        }

        #endregion

        #region [ Слайдер ]

        public ActionResult Slider()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetFilteredSlides(PaginationRequest<BaseFilter> request)
        {
            var response = _sitePageSevice.GetFilteredSlides(request);
            return Json(response);
        }

        public ActionResult AddSlide()
        {
            var model = new BaseResponse<SliderEditModel>(new SliderEditModel());
            return View(model);
        }

        public ActionResult EditSlide(int id)
        {
            var model = _sitePageSevice.GetSlideModel(id);
            return View("~/Areas/Admin/Views/SitePage/AddSlide.cshtml", model);
        }
        
        [HttpPost]
        public ActionResult UpdateSlide(SliderEditModel model)
        {
            var response = model.Id == 0
                ? _sitePageSevice.AddSlide(model)
                : _sitePageSevice.EditSlide(model);
            return RedirectToAction("EditSlide",new {id=response.Value});
        }

        [HttpPost]
        public ActionResult DeleteSlide(int id)
        {
            var response = _sitePageSevice.DeleteSlide(id);
            return Json(response);
        }

        #endregion

        #region [ Города ]

        public ActionResult Cities()
        {
            return View("~/Areas/Admin/Views/SitePage/City.cshtml");
        }

        /// <summary>
        /// Список городов
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetFilteredCities(PaginationRequest<BaseFilter> request)
        {
            var model = _sitePageSevice.GetFilteredCities(request);
            return Json(model);
        }

        /// <summary>
        ///  Обновление города
        /// </summary>
        /// <param name="model">модель с данными</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CityUpdate(DictionaryModel model)
        {
            var response = model.Id == 0
                ? _sitePageSevice.CityAdd(model)
                : _sitePageSevice.CityEdit(model);
            return Json(response);
        }

        /// <summary>
        /// Удаление города
        /// </summary>
        /// <param name="cityId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CityDelete(int cityId)
        {
            var response = _sitePageSevice.CityDelete(cityId);
            return Json(response);
        }

        #endregion
    }
}

CosmeticaShop.Web/Areas/Admin/Views/SitePage/AddSlide.cshtml
@model CosmeticaShop.IServices.Models.Responses.BaseResponse<CosmeticaShop.IServices.Models.Slider.SliderEditModel>
@{
    ViewBag.Title = (Model.Value.Id == 0 ? "Добавление" : "Редактирование") + " слайда";
}

@section breadcrumb
{
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="">CosmeticaShop</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Главная</span>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">@ViewBag.Title</span>
        </li>
    </ul>
}

<div class="row">
    <div class="col-md-12">

        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-green sbold uppercase">@ViewBag.Title</span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="tabbable-line">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#slide" data-toggle="tab">
                                Слайд
                            </a>
                        </li>
                    </ul>
                    @using (Html.BeginForm("UpdateSlide", "SitePage", new { Area = "Admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="form-body form-horizontal">
                            <div class="tab-content">
                                <input name="Id" type="hidden" value="@Model.Value.Id">
                                <div class="tab-pane fade active in" id="slide">
                                    <div class="form-group form-md-line-input">
                                        <label class="control-label col-md-2" for="Photo">Фото</label>
                                        <div class="col-md-8">
                                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 100%; height: 200px;">
                                                    @if (!string.IsNullOrEmpty(Model.Value.PhotoUrl))
                                                    {
                                                        <img src="@Model.Value.PhotoUrl" />
                                                    }
                                                </div>
                                                <div>
                                                    <span class="btn blue btn-file">
                                                        <span class="fileinput-new">
                                                            Выберите изображение
                                                        </span>
                                                        <span class="fileinput-exists">
                                                            Изменить
                                                        </span>
                                                        <input type="file" id="PhotoFile" name="PhotoFile">
                                                    </span>
                                                    <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput">
                                                        Удалить
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group form-md-checkboxes">
                                        <label class="col-md-2 control-label">Видимость</label>
                                        <div class="col-md-10">
                                            <div class="md-checkbox">
                                                @Html.CheckBoxFor(x => x.Value.IsActive, new { @class = "md-check", @id = "IsActive", Name = "IsActive" })
                                                <label for="IsActive">
                                                    <span class="inc"></span>
                                                    <span class="check"></span>
                                                    <span class="box"></span>
                                                    Отображать
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group form-md-line-input">
                                <div class="col-md-offset-2 col-md-10">
                                    <button type="submit" id="save-changes" class="btn blue">Сохранить</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery.liTranslit.js"></script>
    @if (!Model.IsSuccess)
    {
        <script>bootbox.alert('@Model.Message')</script>
    }
}

CosmeticaShop.Web/Areas/Admin/Views/SitePage/City.cshtml
@{
    ViewBag.Title = "Список городов";
}

@section scripts{
    <script src="~/Areas/Admin/assets/js/Form/City/CityModel.js"></script>
    <script src="~/Areas/Admin/assets/js/Form/City/CityFormModel.js"></script>
    <script>
        var params = {};
        params.UrlLoadItems = '@Url.Action("GetFilteredCities", "SitePage")';
        params.UrlSaveChanges = '@Url.Action("CityUpdate", "SitePage")';
        params.UrlDelete = '@Url.Action("CityDelete", "SitePage")';
        params.ModalSelector = '#AddCity';
        var FormModel = new City.CityFormModel(params);
    </script>
}
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN SAMPLE TABLE PORTLET-->
        <div class="portlet light bordered" data-bind="with:FormModel">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-settings font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">Список городов</span>
                </div>
                <div class="actions" data-bind="with:Filter">
                    <button data-toggle="modal" data-target="#AddCity" class="btn btn-success">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-480">
                            Добавить
                        </span>
                    </button>
                    <div class="btn-group btn-group-devided">
                        
                        <div class="input-group" style="width: 300px;">
                            <input data-bind="value:Term" type="text" class="form-control"/>
                            <span class="input-group-btn">
                                <button data-bind="click:FormModel.TableRefresh" class="btn btn-success" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </div>

                </div>
            </div>
            <div class="portlet-body" data-bind="with:Table">
                <div class="table-scrollable">
                    <table class="table table-hover table-light">
                        <thead>
                        <tr>
                            <th> # </th>
                            <th>Наименование</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody data-bind="foreach:Items">
                        <!--ko if: IsEdit() -->
                        <!-- ko template: {name: 'row-edit'}-->
                        <!-- /ko -->
                        <!-- /ko -->
                        <!--ko ifnot: IsEdit() -->
                        <!-- ko template: {name: 'row-default'}-->
                        <!-- /ko -->
                        <!-- /ko -->
                        </tbody>
                    </table>
                </div>
                <pagination data-bind="Component:Pagination"></pagination>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
</div>

<!-- Шаблон вывода -->
<script id="row-default" type="text/html">
    <tr role="row">
        <td data-bind="text:Id"></td>
        <td data-bind="text:Name"></td>
        <td>
            <button data-bind="click:FormModel.ChangeTemplate.bind(FormModel,$data)" class="fa fa-pencil btn btn-sm blue"></button>
            <button data-bind="click:FormModel.DeleteCity.bind(FormModel,$data)" class="fa fa-remove btn btn-sm red"></button>
        </td>
    </tr>
</script>

<!-- Шаблон редактирования -->
<script id="row-edit" type="text/html">
    <tr role="row">
        <td data-bind="text:Id"></td>
        <td>
            <input type="text" data-bind="value:Name, style: { border: (Name() == '' && !IsSuccess()) ? '1px solid red' : '' }" class="form-control">
        </td>
        <td>
            <a data-bind="click:FormModel.SaveChanges.bind(FormModel,$data)" class="fa fa-floppy-o btn btn-sm green"></a>
            <a data-bind="click:FormModel.ResetTemplate.bind(FormModel,$data)" class="fa fa-close btn btn-sm red"></a>
        </td>
    </tr>
</script>

<!-- Модальное окно с формой добавления города -->
<div class="modal fade" id="AddCity" tabindex="-1" role="modal" aria-hidden="true" data-bind="with:FormModel.NewCity">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Добавить новый город <span class="bold"></span></h4>
            </div>
            <div class="modal-body">

                <div class="row form-horizontal">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Наименование</label>
                            <div class="col-md-9">
                                <input type="text" data-bind="value:Name, style: { border: (Name() == '' }" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn default" data-dismiss="modal">Закрыть</button>
                <button type="button" data-dismiss="modal" data-bind="click:FormModel.SaveChanges.bind(FormModel,$data)" class="btn blue">Сохранить</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

CosmeticaShop.Web/Areas/Admin/Views/SitePage/Edit.cshtml
@using CosmeticaShop.IServices.Enums
@using CosmeticaShop.Services.Static
@model CosmeticaShop.IServices.Models.SitePage.SitePageModel
@{
    ViewBag.Title = $"Настройка страницы \"{EnumService.GetEnumDescription(Model.Id)}\"";
}
@section breadcrumb
{
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="">CosmeticaShop</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Страницы</span>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">@ViewBag.Title</span>
        </li>
    </ul>
}
<!-- BEGIN PAGE CONTENT -->
<div class="row">
    <div class="col-md-12">

        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-settings font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">@ViewBag.Title</span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="tabbable-line">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#page" data-toggle="tab">
                                Страница
                            </a>
                        </li>
                    </ul>
                    @using (Html.BeginForm("UpdateSitePage", "SitePage", new { Area = "Admin" }, FormMethod.Post))
                    {
                        <div class="form-body form-horizontal">
                            <div class="tab-content">
                                <input type="hidden" name="Id" value="@Model.Id" />
                                <div class="tab-pane fade active in" id="page">
                                    <div class="form-group form-md-line-input">
                                        <label class="col-md-2 control-label" for="Title">Заголовок</label>
                                        <div class="col-md-10">
                                            <textarea maxlength="128" class="form-control" id="Title" name="Title" rows="2" placeholder="">@Model.Title</textarea>
                                            <div class="form-control-focus">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group form-md-line-input">
                                        <label class="col-md-2 control-label" for="SeoKeywords">SEO Keywords</label>
                                        <div class="col-md-10">
                                            <textarea maxlength="256" class="form-control" id="SeoKeywords" name="SeoKeywords" rows="3" placeholder="">@Model.SeoKeywords</textarea>
                                            <div class="form-control-focus">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group form-md-line-input">
                                        <label class="col-md-2 control-label" for="SeoDescription">SEO Description</label>
                                        <div class="col-md-10">
                                            <textarea maxlength="256" class="form-control" id="SeoDescription" name="SeoDescription" rows="3" placeholder="">@Model.SeoDescription</textarea>
                                            <div class="form-control-focus">
                                            </div>
                                        </div>
                                    </div>
                                    @if (Model.Id != EnumSitePage.Blog && Model.Id!=EnumSitePage.Products)
                                    {
                                        <div class="form-group">
                                            <label class="control-label col-md-2" for="Content">Контент</label>
                                            <div class="col-md-10">
                                                <textarea class="ckeditor form-control" id="Content" name="Content" required="required" rows="6">@Model.Content</textarea>
                                            </div>
                                        </div>
                                    }

                                    @if (Model.Id == EnumSitePage.Contacts)
                                    {
                                        <div class="form-group">
                                            <label class="control-label col-md-2" for="ExtraContent">Доп. контент</label>
                                            <div class="col-md-10">
                                                <textarea class="ckeditor form-control" id="ExtraContent" name="ExtraContent" required="required" rows="6">@Model.ExtraContent</textarea>
                                            </div>
                                        </div>
                                    }
                                </div>
                                <div class="form-group form-md-line-input">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button type="submit" id="Save-Changes" class="btn green">Сохранить</button>
                                    </div>
                                </div>
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END PAGE CONTENT-->

@section scripts{

    <script>

    </script>
}

CosmeticaShop.Web/Areas/Admin/Views/SitePage/Slider.cshtml
@{
    ViewBag.Title = "Список слайдов";
}

@section scripts{
    <script src="~/Areas/Admin/assets/js/Form/Slider/SliderModel.js"></script>
    <script src="~/Areas/Admin/assets/js/Form/Slider/SliderFormModel.js"></script>
    <script>
        var params = {};
        params.UrlLoadItems = '@Url.Action("GetFilteredSlides","SitePage")';
        params.UrlDelete = '@Url.Action("DeleteSlide","SitePage")';
        var FormModel = new Slider.SliderFormModel(params);
    </script>
}
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN SAMPLE TABLE PORTLET-->
        <div class="portlet light bordered" data-bind="with:FormModel">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-settings font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">@ViewBag.Title</span>
                </div>
                <div class="actions">
                    <a class="btn btn-success" href="@Url.Action("AddSlide", "SitePage")">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-480">
                            Добавить
                        </span>
                    </a>
                </div>
            </div>
            <div class="portlet-body" data-bind="with:Table">
                <div class="table-scrollable">
                    <table class="table table-hover table-light">
                        <thead>
                        <tr>
                            <th> # </th>
                            <th></th>
                            <th>Дата создания</th>
                            <th>Видимость</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody data-bind="foreach:Items">
                        <tr>
                            <td data-bind="text:Id"></td>
                            <td>
                                <img data-bind="attr:{src:PhotoUrl()}" width="200">
                            </td>
                            <td data-bind="text:moment(DateCreate()).format('L')"></td>
                            <td>
                                <i data-bind="css:(IsActive()?'fa-check':'fa-close')" class="fa false-icon"></i>
                            </td>
                            <td>
                                <a data-bind="attr:{href:'@Url.Action("EditSlide","SitePage")/'+Id()}" class="fa fa-pencil btn btn-sm blue"></a>
                                <button data-bind="click:FormModel.DeleteSlide.bind(FormModel)" type="button" class="fa fa-remove btn btn-sm red"></button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <pagination data-bind="Component:Pagination"></pagination>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
</div>